name: Publish release to github
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v4.1.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Publish
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release create "v${{github.run_number}}-indev" ${{ steps.export.outputs.build_directory }}/LinuxX11/* --generate-notes
      
      - name: copy file via SCP
        run: scp -r ${{ steps.export.outputs.build_directory }}/LinuxX11 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/OlympiadServer
        
      - name: Run Remote Server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ./startOlympiadServer
